### ISSUE TITLE
Use vagga testing

### ISSUE THREAD

**Issue by andreaferretti** [rrader/vagrant-vagga#4]
Hi, is there a way to use the latest development version of Vagga, as in the `vagga-testing` ubuntu PPA?

**Comment by rrader** [comment]
Now it's hardcoded in https://github.com/rrader/vagrant-vagga/blob/master/lib/vagrant-vagga/setup_vagga.sh#L14

It would be nice to externalize it to the Vagrantfile to be able to change

**Comment by rrader** [comment]
@andreaferretti you can set

```
config.vagga.testing = true
```

in config in new version (0.1.15)
