### ISSUE TITLE
uidmap isn't installed if using an ubuntu version below 14.04

### ISSUE THREAD

**Issue by parhamdoustdar** [rrader/vagrant-vagga#7]
To reproduce this, try provisioning a `hashicorp/precise64` box. You will get an error saying that uidmap cannot be installed. Maybe we need to add the vagga repository for this to work?

**Comment by rrader** [comment]
But why do you need to change the box? Anyway you will use the vagga environment, which is independent of the host (vm) system.

**Comment by parhamdoustdar** [comment]
Oh, sorry, I didn't explain this well enough.

Here are the steps to reproduce this:
1. Create a vagrant machine with `vagrant init hashicorp/precise64`.
2. Add `config.vm.provision :vagga` to the configuration.
3. Now do `vagrant up`.

The box will get provisioned. However, you will see a message saying that `uidmap` could not be found by `apt-get`. If you get an error saying that curl wasn't found (the problem mentioned in #5), do a `vagrant ssh`, then `sudo apt-get install curl` and then exit and do `vagrant provision` to see this issue in action.

**Comment by rrader** [comment]
Right, I mean, is there some reason not to use the "ubuntu/trusty64" box? It's tested on it and works fine.

**Comment by parhamdoustdar** [comment]
Ah. Well, I personally didn't use it because I didn't find anything about a particular box in the README. And, most Vagrant provisioners are platform-independent (as far as installing the provisioner goes, anyway), so I assumed this should work on anything Vagga supports.

It's okay if this is not the goal of the project. As I said in another issue, I'm new to the project and I'm not familiar with the goals, so please bear with me while I make suggestions you may not like. :-)

**Comment by rrader** [comment]
Oh, no problem. I just wanted to be sure there's no particular reason.
There's example Vagrantfile in README. Actually I agree it's good to fix, but if it's not required, use the Vagrantfile from README.

```
unless Vagrant.has_plugin?("vagrant-vagga")
  abort 'vagrant-vagga plugin is not installed! Do first # vagrant plugin install vagrant-vagga'
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :vagga
end
```

**Comment by rrader** [comment]
The goal of the project is to make the portable Vagga, not the plugin itself. If there will be better way to bring vagga to other operating systems, we will move from Vagrant to another solution, but no such tries made so far.

**Comment by rrader** [comment]
Thank you for the reporting btw! I just added installation of the `uidmap`, but I see new issue. Will open new ticket and see

**Comment by parhamdoustdar** [comment]
Thanks a lot for beginning to implement this! I was going to suggest to wait and see if anyone else needs this. :-)

I personally switched to ubuntu-trusty64 for now. No need to use an older release when it doesn't make any sense.
