### ISSUE TITLE
Ubuntu precise64: error when forking: Operation not permitted

### ISSUE THREAD

**Issue by rrader** [rrader/vagrant-vagga#8]
While fixing the #7 new issue appeared.
Vagrantfile:

```
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"

  config.vagga.install = true
  config.vagga.testing = false

  config.vm.provision :vagga
end
```

Vagga returns

```
$ vagrant vagga test
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: VirtualBox VM is already running.
error when forking: Operation not permitted (os error 1)
```

```
$ cat /etc/subgid 
vagrant:100000:65536
$ cat /etc/subuid 
vagrant:100000:65536
```

```
# uname -a
Linux precise64 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rrader** [comment]
As per documentation http://vagga.readthedocs.org/en/latest/errors.html#root

> Check uname -r to have version of 3.9 or greater

the kernel is older than required, but support of the Precise version is declared in doc, so maybe it's configuration issues.

@tailhook, can you please take a look?

**Comment by tailhook** [comment]
Sure, precise works. You just have to upgrade the kernel. There are tens of kernels available for each ubuntu release. Some of them are buggy, though. IIRC, they are called `linux-image-*`. I have `3.16.0-37-generic` installed on some of my ubuntus if that helps.

**Comment by rrader** [comment]
Ah, so the issue is in kernel. Ok, thank you.
